### ISSUE TITLE
I want to konwn how to do the Multi-way Registration? thanks

### ISSUE THREAD

**Issue by BiaoBiaoLi** [chrischoy/DeepGlobalRegistration#14]
In this section
**5.2. Multi-way Registration
Multi-way registration for RGB-D scans proceeds via multiple stages. First, the pipeline estimates the camera pose via off-the-shelf odometry and integrates multiple 3D scans to reduce noise and generate accurate 3D fragments of a scene. Next, a pairwise registration algorithm roughly aligns all fragments, followed by multi-way registration [6] which optimizes fragment poses with robust pose graph optimization.**
I want to know in the fisrt stage,  if you use the groud truth of these datasets ? 
thanks

**Comment by theNded** [comment]
No, we used Open3D's RGB-D odometry. We replaced RANSAC/FGR with DGR in this system https://github.com/intel-isl/Open3D/tree/master/examples/python/reconstruction_system

**Comment by BiaoBiaoLi** [comment]
thank you very much, I haven't studied this before.
if you use the all  RGB-D images to reconstruct ? 
and if you use the camera pose estimated for pairwise registration as initialization in Multi-way Registration?
