### ISSUE TITLE
I want to know how to set the  n_frames_per_fragment of open3d in section 5.2. Multi-way Registration?

### ISSUE THREAD

**Issue by BiaoBiaoLi** [chrischoy/DeepGlobalRegistration#16]
thanks your work.
In this section
5.2. Multi-way Registration
Multi-way registration for RGB-D scans proceeds via multiple stages. First, the pipeline estimates the camera pose via off-the-shelf odometry and integrates multiple 3D scans to reduce noise and generate accurate 3D fragments of a scene. Next, a pairwise registration algorithm roughly aligns all fragments, followed by multi-way registration [6] which optimizes fragment poses with robust pose graph optimization.
I want to know in the fisrt stage,  in order to generate accurate 3D fragments
of a scene and make sure  that each fragment contains enough geometric features, how to set the  n_frames_per_fragment of open3d ? 
thanks

**Comment by theNded** [comment]
Please refer to the Open3D's config, '*_simulated.json' in
https://github.com/intel-isl/Open3D/tree/master/examples/python/reconstruction_system/config/redwood_simulated.

**Comment by BiaoBiaoLi** [comment]
ok，thanks，i get it！！！
