### ISSUE TITLE
I want to know how to define the the absolute trajectory error (ATE)  in section 5.2. Multi-way Registration and how to calculate it? 

### ISSUE THREAD

**Issue by BiaoBiaoLi** [chrischoy/DeepGlobalRegistration#17]
thanks your work !
I want to know how to define the the absolute trajectory error (ATE)  in section 5.2. Multi-way Registration and how to calculate it? 
Is it translation error between the rigid tranformation first fragment to the last fragment ?
Ground-truth Trajectory in http://redwood-data.org/indoor/dataset.html

**Comment by theNded** [comment]
Open3D outputs `trajectory.log` in `scene`. Compare its poses against gt frame-by-frame will give you the ATE.

**Comment by junha-l** [comment]
@theNded Hi, 
Would you mind sharing how to compare the poses?
To my understanding, one can measure the difference of translation vector between every pair of poses and calculate RMSE over these values to get ATE, but I'm not sure if it is the exact definition of ATE.
