### ISSUE TITLE
Is there a recommend implementations on RANSAC, Go-ICP etc

### ISSUE THREAD

**Issue by hansen7** [chrischoy/DeepGlobalRegistration#18]
Hi, @chrischoy and @theNded , thanks for sharing this code!

It would be helpful if you can recommend/share me with some implementations on the RANSAC, Go-ICP methods?

**Comment by theNded** [comment]
For RANSAC please refer to an up-to-date implementation in Open3D: https://github.com/intel-isl/Open3D/blob/master/examples/python/pipelines/global_registration.ipynb
For Go-ICP you have to use its official implementation or its python binding https://github.com/yangjiaolong/Go-ICP.

**Comment by hansen7** [comment]
Thanks!

**Comment by DavidBoja** [comment]
Could you comment on the parameters used for GO-ICP? 
I cannot achieve the 22.9% recall you mention in your paper.
