### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'has_bias' 

### ISSUE THREAD

**Issue by gaojunjie1234** [chrischoy/DeepGlobalRegistration#19]

**Comment by MickShen7558** [comment]
Hi Guojunjie, I am having the same issue. Have you solved that problem? How did you fix that?

**Comment by gaojunjie1234** [comment]
i choose the V0.4.3, and solved this problem.
you can try to replace has_bias with bias, but i'm not sure it could work.


| |
高俊杰
|
|
gjjsdnu@163.com
|
签名由网易邮箱大师定制
On 12/29/2020 22:49，Zhuowen Shen<notifications@github.com> wrote：

Hi Guojunjie, I am having the same issue. Have you solved that problem? How did you fix that?

**Comment by MickShen7558** [comment]
I was using the other version. After changing to V0.4.3, it works. Thanks a lot!
