### ISSUE TITLE
Possibility to use Deep Global Registration without MinkowskiEngine

### ISSUE THREAD

**Issue by kaixin-bai** [chrischoy/DeepGlobalRegistration#25]
Is that possible to use deep global registration without MinkowskiEngine? I want to test deep global registration but cannot install MinkowskiEngine successfully. It seems that MinkowskiEngine has a bug because of GCC, I must update Cuda version to 11.0 to avoid the problem, but I don't have sudo, and cannot update cuda.

**Comment by r-dh** [comment]
In my experience this project doesn't work with the latest MinkowskiEngine. You'll have to install MinkowskiEngine v4.3.0 which can't be installed with CUDA 11.0, I had to use 10.1.

Make sure to explicitly add ` export CUDA_HOME=/usr/local/cuda-10.1;`  to install MinkowskiEngine.
