### ISSUE TITLE
Questions regarding the outlier rejection module.

### ISSUE THREAD

**Issue by XuyangBai** [chrischoy/DeepGlobalRegistration#4]
Hi Chris @chrischoy 

Thanks for sharing this interesting work. I wonder have you tried the Context Normalization in the outlier filtering module, which is commonly used in 2D outlier rejection methods? And will using some pre-filtering strategies like mutual check or ratio test give better performance to your network?

Best,
Xuyang.

**Comment by chrischoy** [comment]
Yes, I tried on the High-Dimensional Convolutional Networks for Geometric Pattern Recognition, CVPR'20 and found that it cannot be trained well with the 360 rotation augmentation, and leading to lower performance.
