### ISSUE TITLE
Scale translation in kitti_loader.py

### ISSUE THREAD

**Issue by caoquan95** [chrischoy/DeepGlobalRegistration#6]
Hello,

Thank you for your great work. 
In file https://github.com/chrischoy/DeepGlobalRegistration/blob/master/dataloader/kitti_loader.py
from line 176 to 182.

I don't see you scale the ground truth translation. Is it a bug?

**Comment by chrischoy** [comment]
No its not a bug.

It's already in m.

**Comment by caoquan95** [comment]
I don't see how is it related to SI units?

I thought if we scale the 2 point clouds, we also need to scale the translation between them.

**Comment by chrischoy** [comment]
Please read the evaluation metrics and how the features are extracted.
